version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojectaws_john -Dsonar.organization=javaprojectaws_john -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=e80046003270ed0e21c22884bfb5339547663bf2
 
