version: 0.2
phases:
  install:
    runtime-versions:
      java: 17
  build:
    commands:
      - echo "Running static code analysis with SonarCloud"
      - mvn verify sonar:sonar -Dsonar.projectKey=tes-test_awsdevsecops -Dsonar.organization=test-test -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=6996c0bd0e7055b92c575cbc8e86c6025505f35f
